"""added timestamps to remaining objects

Revision ID: 4a4a433dbbe4
Revises: cc4a74b96ed7
Create Date: 2023-10-11 15:08:50.433532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a4a433dbbe4'
down_revision: Union[str, None] = 'cc4a74b96ed7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurant_lists', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('restaurants', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('tags', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'created_at')
    op.drop_column('tags', 'created_at')
    op.drop_column('restaurants', 'created_at')
    op.drop_column('restaurant_lists', 'created_at')
    # ### end Alembic commands ###
