"""added back foreign keys

Revision ID: 896aabfdc472
Revises: 47e395b33202
Create Date: 2023-09-08 20:50:52.957942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '896aabfdc472'
down_revision: Union[str, None] = '47e395b33202'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pictures', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.add_column('pictures', sa.Column('rating_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'pictures', 'users', ['owner_id'], ['id'])
    op.create_foreign_key(None, 'pictures', 'ratings', ['rating_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pictures', type_='foreignkey')
    op.drop_constraint(None, 'pictures', type_='foreignkey')
    op.drop_column('pictures', 'rating_id')
    op.drop_column('pictures', 'owner_id')
    # ### end Alembic commands ###
