"""enabled shared lists

Revision ID: 8ca8b0216a02
Revises: 14339a98ac1d
Create Date: 2023-09-27 14:12:28.087485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ca8b0216a02'
down_revision: Union[str, None] = '14339a98ac1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('list_user_association',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('list_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['list_id'], ['restaurant_lists.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'list_id')
    )
    op.drop_constraint('restaurant_lists_owner_id_fkey', 'restaurant_lists', type_='foreignkey')
    op.drop_column('restaurant_lists', 'owner_id')
    op.alter_column('tag_association', 'restaurant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('tag_association', 'tag_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tag_association', 'tag_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('tag_association', 'restaurant_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('restaurant_lists', sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('restaurant_lists_owner_id_fkey', 'restaurant_lists', 'users', ['owner_id'], ['id'])
    op.drop_table('list_user_association')
    # ### end Alembic commands ###
