"""followers/following

Revision ID: cc4a74b96ed7
Revises: 72ed8272aad3
Create Date: 2023-10-10 18:47:20.724617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc4a74b96ed7'
down_revision: Union[str, None] = '72ed8272aad3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers_association',
    sa.Column('follower_id', sa.UUID(), nullable=True),
    sa.Column('followed_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
