name: deploy-to-dev

on:
  push:
    branches: [ develop ]
    
  workflow_dispatch:

jobs:
  build:
    runs-on:
      - self-hosted
    strategy: 
      matrix:
        node-version: [16.x]
    
    steps:
      - uses: actions/checkout@v2
      
      - name: do install
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: yarn clean
      - run: |
          touch .env
          echo "${{ secrets.DEV_ENV_FILE }}" > .env
      - run: yarn run dev
        
    
  
  

