name: fast-api-dev-deploy

on:
  push:
    branches: [ develop ]
    
  workflow_dispatch:

jobs:
  build:
    runs-on:
      - self-hosted
    
    steps:
      - uses: actions/checkout@v2

      # Step-1 Create .env file from repo secrets
      - name: Create .env File
        run: |
          touch .env
          echo "${{ secrets.DEV_ENV_FILE }}" > .env

      # CACHING IS TO BE IMPLEMENTED
      # # https://docs.github.com/en/actions/guides/caching-dependencies-to-speed-up-workflows
      # - name:  Virtual ENV
      #   uses: actions/cache@v2
      #   id: cache-venv # name for referring later
      #   with:
      #     path: venv # what we cache: the Virtual ENV
      #     # The cache key depends on requirements.txt
      #     key: ${{ runner.os }}-venv-${{ hashFiles('**/requirements*.txt') }}
      #     restore-keys: |
      #       ${{ runner.os }}-venv-

      # Step-2 Build a Virtual ENV, and Download packages
      - name: Activate Virtual ENV, and Download Packages
        run: python3 -m pipenv shell 
        # if: steps.cache-venv.outputs.cache-hit != 'true'

      - name: Download packages
        run: python3 -m pipenv install

      #Step-3 Restart the API
      - name: Restart API
        run: pm2 restart api
