name: fast-api-dev-deploy

on:
  push:
    branches: [ develop ]
    
  workflow_dispatch:

jobs:
  build:
    runs-on:
      - self-hosted
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python
        # This action sets up a Python environment for use in actions
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
          # optional: architecture: x64 x64 or x86. Defaults to x64 if not specified

      # Step-2 Install Python Virtual ENV
      - name: Install Python Virtual ENV
        run: pip3 install virtualenv

      # Step-3 Cache Virtual ENV
      # https://docs.github.com/en/actions/guides/caching-dependencies-to-speed-up-workflows
      - name:  Virtual ENV
        uses: actions/cache@v2
        id: cache-venv # name for referring later
        with:
          path: venv # what we cache: the Virtual ENV
          # The cache key depends on requirements.txt
          key: ${{ runner.os }}-venv-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-venv-

      # Step-4 Build a Virtual ENV, but only if it doesn't already exist
      - name: Activate Virtual ENV
        run: python3 -m venv venv && source venv/bin/activate
        if: steps.cache-venv.outputs.cache-hit != 'true'

      #Step-5 Download required packages
      - name: Download Required Packages
        run: pip3 install -r requirements.txt

      #Step-6 Restart 
      - name: Restart API
        run: pm2 restart api
