name: fast-api-dev-deploy

on:
  push:
    branches: [ develop ]
    
  workflow_dispatch:

jobs:
  build:
    runs-on:
      - self-hosted
    
    steps:
      - uses: actions/checkout@v2

      # Step-1 Install Python Virtual ENV
      - name: Install Python Virtual ENV
        run: pip3 install virtualenv

      # Step-2 Cache Virtual ENV
      # https://docs.github.com/en/actions/guides/caching-dependencies-to-speed-up-workflows
      - name:  Virtual ENV
        uses: actions/cache@v2
        id: cache-venv # name for referring later
        with:
          path: venv # what we cache: the Virtual ENV
          # The cache key depends on requirements.txt
          key: ${{ runner.os }}-venv-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-venv-

      # Step-3 Build a Virtual ENV, and Download packages
      - name: Activate Virtual ENV, and Download Packages
        run: python3 -m venv venv && source venv/bin/activate && pip3 install -r requirements.txt
        if: steps.cache-venv.outputs.cache-hit != 'true'

      #Step-4 Restart the API
      - name: Restart API
        run: pm2 restart api
